name: user_repository
description: UserRepository example for flutter_login.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6
  http: ^0.12.0+2
  json_annotation: ^3.0.0
  uuid: ^2.0.0
  get_version: ^0.0.8+5
  flutter_whatsnew: ^0.2.0+3
  cupertino_icons: ^0.1.2
  persist_theme: ^0.0.3+6
  scoped_model: ^1.0.1
  flutter_platform_widgets: "^0.20.3-beta.1"
flutter:
  uses-material-design: true